export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_BOOK_FROM_CART = "DELETE_BOOK_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREASE_BOOK_COUNT = "INCREASE_BOOK_COUNT";
export const DECREASE_BOOK_COUNT = "DECREASE_BOOK_COUNT";
export const MAKE_ISINCART_TRUE = "MAKE_IS_IN_CART_TRUE";