// for cartActions
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_BOOK_FROM_CART = "DELETE_BOOK_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREASE_BOOK_COUNT = "INCREASE_BOOK_COUNT";
export const DECREASE_BOOK_COUNT = "DECREASE_BOOK_COUNT";
export const MAKE_ISINCART_TRUE = "MAKE_IS_IN_CART_TRUE";
// for bookActions
export const MAKE_ISINCART_FALSE = "MAKE_ISINCART_FALSE";
export const MAKE_IS_IN_WISHLIST_FALSE = "MAKE_IS_IN_WISHLIST_FALSE";
export const MAKE_IS_IN_COMPARE_FALSE = "MAKE_IS_IN_COMPARE_FALSE";
export const SORT_BOOKS_BY_NAME_AND_PRICE = "SORT_BOOKS_BY_NAME_AND_PRICE";
export const SORT_BOOKS_BY_GENRE = "SORT_BOOKS_BY_GENRE";
export const SEARCH_BOOK = "SEARCH_BOOK";
// for wishlistActions
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const MAKE_IS_IN_WISHLIST_TRUE_IN_WISHLIST = "MAKE_IS_IN_WISHLIST_TRUE_IN_WISHLIST";
export const MAKE_WISHLIST_BOOK_ISINCART_FALSE = "MAKE_WISHLIST_BOOK_ISINCART_FALSE";
// for compareActions
export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";
export const MAKE_IS_IN_COMPARE_TRUE_IN_COMPARE = "MAKE_IS_IN_COMPARE_TRUE_IN_COMPARE";
export const MAKE_COMPARE_BOOK_ISINCART_FALSE = "MAKE_COMPARE_BOOK_ISINCART_FALSE";